let albums = [
  {
    id: "1",
    name: "LOI CHOI",
    artist: "Wren Evans, isnk",
    src: "/Resources/Images2/loiChoi.jfif",
  },
  {
    id: "2",
    name: "99%",
    artist: "RPT MCK",
    src: "/Resources/Images2/99percent.jfif",
  },
  {
    id: "3",
    name: "ái",
    artist: "tlinh",
    src: "/Resources/Images2/ai.jfif",
  },
  {
    id: "4",
    name: "Đẹp",
    artist: "MONO",
    src: "/Resources/Images2/emXinh.jfif",
  },
  {
    id: "5",
    name: "22",
    artist: "MONO",
    src: "/Resources/Images2/22.jfif",
  },
  {
    id: "6",
    name: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
    artist: "HIEUTHUHAI",
    src: "/Resources/Images2/aiCungPhai.jfif",
  },
];
let artists = [
  {
    id: "7",
    name: "Sơn Tùng M-TP",
    artist: "Artist",
    src: "/Resources/Images2/sonTung.jfif",
  },
  {
    id: "8",
    name: "MONO",
    artist: "Artist",
    src: "/Resources/Images2/mono.jfif",
  },
  {
    id: "9",
    name: "RPT-MCK",
    artist: "Artist",
    src: "/Resources/Images2/rptMck.jfif",
  },
  {
    id: "10",
    name: "tlinh",
    artist: "Artist",
    src: "/Resources/Images2/tlinh.jfif",
  },
  {
    id: "11",
    name: "Wren Evans",
    artist: "Artist",
    src: "/Resources/Images2/wrenEvans.jfif",
  },
  {
    id: "12",
    name: "HIEUTHUHAI",
    artist: "Artist",
    src: "/Resources/Images2/HIEUTHUHAI.jfif",
  },
];
let radios = [
  {
    id: "1",
    name: "Low G Radio",
    artist: "With Obito, Ngơ, RPT MCK and more",
    src: "/Resources/Images2/Radio0.jfif",
  },
  {
    id: "2",
    name: "HIEUTHUHAI Radio",
    artist: "With Obito, Bray, RPT MCK and more",
    src: "/Resources/Images2/Radio1.jfif",
  },
  {
    id: "3",
    name: "Vu. Radio",
    artist: "With Hoàng Dũng, Da LAB, Chillies and more",
    src: "/Resources/Images2/Radio2.jfif",
  },
  {
    id: "4",
    name: "Sơn Tùng M-TP Radio",
    artist: "With MONO, Đen, SOOBIN and more",
    src: "/Resources/Images2/Radio3.jfif",
  },
  {
    id: "5",
    name: "RPT MCK Radio",
    artist: "With Wxrdie, Obito, Ngơ and more",
    src: "/Resources/Images2/Radio4.jfif",
  },
  {
    id: "6",
    name: "Taylor Swift Radio",
    artist: "With SelenaGomez, Olivia Rodrigo and more ",
    src: "/Resources/Images2/Radio5.jfif",
  },
];
localStorage.setItem("albums", JSON.stringify(albums));
localStorage.setItem("artists", JSON.stringify(artists));
localStorage.setItem("radios", JSON.stringify(radios));
let item = JSON.parse(localStorage.getItem("albums"));
let item1 = JSON.parse(localStorage.getItem("radios"));
let item2 = JSON.parse(localStorage.getItem("artists"));

const doduLieu = (s, item) => {
  let html = "";
  html = item.map((i) => {
    return ` <a href="index4.html?detail=${i.id}">
    <li class="item">
    <img src="${i.src}">
    <div class="play-btn"><span><i class="fa-solid fa-play"></i></span></div>
    <h4>${i.name}</h4>
    <p>${i.artist}</p>
    </li>
  </a>`;
  });
  document.querySelector(`.${s}`).innerHTML = html.join("");
  console.log(html);
};
doduLieu("albums", item);
doduLieu("artists", item2);
doduLieu("radios", item1);
//______________________________________________________________________________________________________-
let albums_detail = [
  {
    idparent: "1",
    id: "1",
    name: `Phóng Đổ Tim Em`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - Phóng Đổ Tim Em - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "1",
    id: "2",
    name: `CALL ME`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - CALL ME - OFFICIAL MUSIC VIDEO.mp3",
  },
  {
    idparent: "1",
    id: "3",
    name: `Cầu Vĩnh Tuy`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - Cầu Vĩnh Tuy - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "1",
    id: "4",
    name: `Từng Quen`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/TỪNG QUEN - WREN EVANS X LIM FENG.mp3",
  },
  {
    idparent: "1",
    id: "5",
    name: `bé ơi từ từ`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - bé ơi từ từ - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "1",
    id: "6",
    name: `Lối Chơi (Interlude)`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - Lối Chơi (Interlude) - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "1",
    id: "7",
    name: `Tình Yêu Vĩ Mô`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - Tình Yêu Vĩ Mô - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "1",
    id: "8",
    name: `Việt Kiều`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - VIỆT KIỀU (ft. itsnk, starring @oanhdaqueen) - OFFICIAL MUSIC VIDEO.mp3",
  },
  {
    idparent: "1",
    id: "9",
    name: `ĐĐĐ`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - ĐĐĐ - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "1",
    id: "10",
    name: `Quyền Anh`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - Quyền Anh - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "1",
    id: "11",
    name: `Tò Te Tí`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - Tò Te Tí - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "2",
    id: "12",
    name: `00`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/00.mp3",
  },
  {
    idparent: "2",
    id: "13",
    name: `Chìm Sâu`,
    artist: "RPT MCK, Trung Trần",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/Chìm Sâu - RPT MCK (feat. Trung Trần) - Official Lyrics Video.mp3",
  },
  {
    idparent: "2",
    id: "14",
    name: `Suit & Tie`,
    artist: "RPT MCK, Hoàng Tôn",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/03. Suit & Tie - RPT MCK ( ft. Hoàng Tôn ) - - 99_ - the album.mp3",
  },
  {
    idparent: "2",
    id: "15",
    name: `Va Vào Giai Điệu Này`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/04. Va Vào Giai Điệu Này - RPT MCK - -99_- the album.mp3",
  },
  {
    idparent: "2",
    id: "16",
    name: `Tối Nay Ta Đi Đâu Nhỉ`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/Tối Nay Ta Đi Đâu Nhờ.mp3",
  },
  {
    idparent: "2",
    id: "17",
    name: `Chỉ Một Đêm Nữa Thôi`,
    artist: "RPT MCK, tlinh",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/06. Chỉ Một Đêm Nữa Thôi - RPT MCK ( ft. tlinh ) - - 99_ - the album.mp3",
  },
  {
    idparent: "2",
    id: "18",
    name: `Thôi Em Đùng Đi`,
    artist: "RPT MCK, Trung Trần",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/07. Thôi Em Đừng Đi - RPT MCK ( ft. Trung Trần ) - - 99_ - the album.mp3",
  },
  {
    idparent: "2",
    id: "19",
    name: `50/50`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/50-50.mp3",
  },
  {
    idparent: "2",
    id: "20",
    name: `Cuốn Cho Anh Một Điếu Nữa Đi`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/09. Cuốn Cho Anh Một Điếu Nữa Đi - RPT MCK - - 99_ - the album.mp3",
  },
  {
    idparent: "2",
    id: "21",
    name: `Show Me Love`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/10. Show Me Love - RPT MCK - - 99_ - the album.mp3",
  },
  {
    idparent: "2",
    id: "22",
    name: `Tại  Vì Sao`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/RPT MCK - TẠI VÌ SAO - Official Music Video.mp3",
  },
  {
    idparent: "2",
    id: "23",
    name: `Thờ Er`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/RPT MCK - TẠI VÌ SAO - Official Music Video.mp3",
  },
  {
    idparent: "2",
    id: "24",
    name: `Ai Mới Là Kẻ Xâu Xa`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/RPT MCK - AI MỚI LÀ KẺ XẤU XA - OFFICIAL MUSIC VIDEO.mp3",
  },
  {
    idparent: "2",
    id: "25",
    name: `Anh Đã Ổn Hơn`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/14. Anh Đã Ổn Hơn - RPT MCK - -99_- the album.mp3",
  },
  {
    idparent: "2",
    id: "26",
    name: `Badtrip`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/15. Badtrip - RPT MCK - -99_- the album.mp3",
  },
  {
    idparent: "2",
    id: "27",
    name: `99`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/16. 99 - RPT MCK - -99_- the album.mp3",
  },
  {
    idparent: "3",
    id: "28",
    name: `tình yêu có nghĩa là gì?`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - người đẹp ngủ - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "3",
    id: "29",
    name: `người đẹp ngủ`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - người đẹp ngủ - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "3",
    id: "30",
    name: `người điên`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - người điên - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "3",
    id: "31",
    name: `kho báu đánh rơi (feat.GREY D)`,
    artist: "tlinh, GREY D",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - kho báu đánh rơi (feat. Grey D) - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "3",
    id: "32",
    name: `ái`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - ái (interlude) - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "3",
    id: "33",
    name: `làm lành chữa tình`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - làm lành chữa tình - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "3",
    id: "34",
    name: `thế giới thần tiên`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - thế giới thần tiên - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "3",
    id: "35",
    name: `những đốm sáng`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - những đốm sáng - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "3",
    id: "36",
    name: `nữ siêu anh hùng`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - nữ siêu anh hùng - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "3",
    id: "37",
    name: `ghệ yêu dấu của em ơi`,
    artist: "tlinh, 2pillz, WOKEUP",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - ghệ iu dấu của em ơi - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "3",
    id: "38",
    name: `nếu lúc đó`,
    artist: "tlinh, 2pillz",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - nếu lúc đó - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "3",
    id: "39",
    name: `kết thúc =  mở đầu`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - kết thúc = mở đầu (outro) - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "4",
    id: "40",
    name: `Intro`,
    artist: "MONO",
    image: "/Resources/Images2/emXinh.jfif",
    path: "/Resources/emxinh/Intro.mp3",
  },
  {
    idparent: "4",
    id: "41",
    name: `Cười Lên`,
    artist: "MONO",
    image: "/Resources/Images2/emXinh.jfif",
    path: "/Resources/emxinh/MONO - CƯỜI LÊN (Official Audio).mp3",
  },
  {
    idparent: "4",
    id: "42",
    name: `Em Xinh`,
    artist: "MONO, Onionn",
    image: "/Resources/Images2/emXinh.jfif",
    path: "/Resources/emxinh/MONO - Em Xinh (Official Music Video).mp3",
  },
  {
    idparent: "4",
    id: "43",
    name: `Young`,
    artist: "MONO",
    image: "/Resources/Images2/emXinh.jfif",
    path: "/Resources/emxinh/MONO - 'OPEN YOUR EYES (Official Audio).mp3",
  },
  {
    idparent: "4",
    id: "44",
    name: `Open Your Eyes`,
    artist: "MONO, Onionn",
    image: "/Resources/Images2/emXinh.jfif",
    path: "/Resources/emxinh/MONO - 'OPEN YOUR EYES (Official Audio).mp3",
  },
  {
    idparent: "5",
    id: "45",
    name: `Intro`,
    artist: "MONO",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/INTRO.mp3",
  },
  {
    idparent: "5",
    id: "46",
    name: `Buông`,
    artist: "MONO",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - Buông (Album 22 - Track No.02).mp3",
  },
  {
    idparent: "5",
    id: "47",
    name: `Em Là`,
    artist: "MONO, Onionn",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - Em Là (Album 22 - Track No.03).mp3",
  },
  {
    idparent: "5",
    id: "48",
    name: `Kill Me`,
    artist: "MONO",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - Kill Me (Album 22 - Track No.04).mp3",
  },
  {
    idparent: "5",
    id: "49",
    name: `Quên Anh Đi`,
    artist: "MONO",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - Quên Anh Đi (Album 22 - Track No.05).mp3",
  },
  {
    idparent: "5",
    id: "50",
    name: `Anh Không Thể`,
    artist: "MONO, Onionn",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - Anh Không Thể (Album 22 - Track No.07).mp3",
  },
  {
    idparent: "5",
    id: "51",
    name: `Do You`,
    artist: "MONO, Rein, Onionn",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO ft Rein - Do You (Album 22 - Track No.08).mp3",
  },
  {
    idparent: "5",
    id: "52",
    name: `Cô nương Ahhhh~`,
    artist: "MONO",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/_MONO - Cô Nương AHHHhhhh. (Album 22 - Track No.09).mp3",
  },
  {
    idparent: "5",
    id: "53",
    name: `Waiting For You`,
    artist: "MONO, Onionn",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - Waiting For You (Album 22 - Track No.10).mp3",
  },
  {
    idparent: "5",
    id: "54",
    name: `L.I.E`,
    artist: "MONO, Onionn",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - L.I.E (Album 22 - Track No.11).mp3",
  },
  {
    idparent: "6",
    id: "55",
    name: `Ai Cũng Phải Bắt Đầu Từ Đó`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Ai Cũng Phải Bắt Đầu Từ Đâu Đó (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "6",
    id: "56",
    name: `Giờ Thì Ai Cười`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Giờ Thì Ai Cười (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "6",
    id: "57",
    name: `Không Phải Gu`,
    artist: "HIEUTHUHAI,B Ray, Tage",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Không Phải Gu (prod. by Kewtiie) ft. B Ray & Tage [Official Lyric Video].mp3",
  },
  {
    idparent: "6",
    id: "58",
    name: `Siêu Sao`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Siêu Sao (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "6",
    id: "60",
    name: `Đi Họp Lớp`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Đi Họp Lớp (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "6",
    id: "61",
    name: `Không Thể Say`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Không Thể Say (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "6",
    id: "62",
    name: `Exit Sign`,
    artist: "HIEUTHUHAI,marzuz",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Exit Sign (prod. by Kewtiie) ft. marzuz [Official Lyric Video].mp3",
  },
  {
    idparent: "6",
    id: "63",
    name: `Visa Interlude`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Visa Interlude (prod. by Kewtiie) [Official Audio].mp3",
  },
  {
    idparent: "6",
    id: "64",
    name: `Sắp Nổi Tiếng`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Sắp Nổi Tiếng (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "6",
    id: "65",
    name: `KPI`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - KPI (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "6",
    id: "66",
    name: `Everything Will Be Okay`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Everything Will Be Okay (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "6",
    id: "67",
    name: `Cho Em An Toàn`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Cho Em An Toàn (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "6",
    id: "68",
    name: `NOLOVENOLIFE`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - NOLOVENOLIFE (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "7",
    id: "69",
    name: `Chúng Ta Của Tương Lai`,
    artist: "Son Tung M-TP",
    image: "/Resources/Images2/chungTaCuaTuongLai.jfif",
    path: "/Resources/mtp/SƠN TÙNG M-TP - CHÚNG TA CỦA TƯƠNG LAI - OFFICIAL MUSIC VIDEO.mp3",
  },
  {
    idparent: "7",
    id: "70",
    name: `Chúng Ta Của Hiện Tại`,
    artist: "Son Tung M-TP",
    image: "/Resources/Images2/chungTaCuaHienTai.jfif",
    path: "/Resources/mtp/Chúng Ta Của Hiện Tại.mp3",
  },
  {
    idparent: "7",
    id: "76",
    name: "MAKING MY WAY",
    artist: "Son Tung M-TP",
    image: "/Resources/Images2/MAKINGMYWAY.jfif",
    path: "/Resources/mtp/making-my-way-son-tung-m-tp.mp3",
  },
  {
    idparent: "7",
    id: "71",
    name: `Muộn Rồi Mà Sao Còn`,
    artist: "Son Tung M-TP",
    image: "/Resources/Images2/muonRoiMaSaoCon.jfif",
    path: "/Resources/mtp/SƠN TÙNG M-TP - MUỘN RỒI MÀ SAO CÒN - OFFICIAL MUSIC VIDEO.mp3",
  },
  {
    idparent: "7",
    id: "72",
    name: `Có Chắc Yêu Là Đây`,
    artist: "Son Tung M-TP",
    image: "/Resources/Images2/coChacYeuLaDay.jfif",
    path: "/Resources/mtp/SƠN TÙNG M-TP - CÓ CHẮC YÊU LÀ ĐÂY - OFFICIAL MUSIC VIDEO.mp3",
  },
  {
    idparent: "7",
    id: "73",
    name: `Chạy Ngay Đi`,
    artist: "Son Tung M-TP",
    image: "/Resources/Images2/chayNgayDi.jfif",
    path: "/Resources/mtp/CHẠY NGAY ĐI - RUN NOW - SƠN TÙNG M-TP - Official Music Video.mp3",
  },
  {
    idparent: "7",
    id: "74",
    name: `THERE'S NO ONE AT ALL`,
    artist: "Son Tung M-TP",
    image: "/Resources/Images2/THERE'SNOONEATALL.jfif",
    path: "/Resources/mtp/SƠN TÙNG M-TP - THERES NO ONE AT ALL (ANOTHER VERSION) - OFFICIAL MUSIC VIDEO.mp3",
  },
  {
    idparent: "7",
    id: "75",
    name: "Lạc Trôi",
    artist: "Son Tung M-TP",
    image: "/Resources/Images2/lacTroi.jfif",
    path: "/Resources/mtp/LẠC TRÔI - OFFICIAL MUSIC VIDEO - SƠN TÙNG M-TP.mp3",
  },
  {
    idparent: "8",
    id: "53",
    name: `Waiting For You`,
    artist: "MONO, Onionn",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - Waiting For You (Album 22 - Track No.10).mp3",
  },
  {
    idparent: "8",
    id: "42",
    name: `Em Xinh`,
    artist: "MONO, Onionn",
    image: "/Resources/Images2/emXinh.jfif",
    path: "/Resources/emxinh/MONO - Em Xinh (Official Music Video).mp3",
  },
  {
    idparent: "8",
    id: "43",
    name: `Young`,
    artist: "MONO",
    image: "/Resources/Images2/emXinh.jfif",
    path: "/Resources/emxinh/MONO - 'OPEN YOUR EYES (Official Audio).mp3",
  },
  {
    idparent: "8",
    id: "44",
    name: `Open Your Eyes`,
    artist: "MONO, Onionn",
    image: "/Resources/Images2/emXinh.jfif",
    path: "/Resources/emxinh/MONO - 'OPEN YOUR EYES (Official Audio).mp3",
  },
  {
    idparent: "8",
    id: "46",
    name: `Buông`,
    artist: "MONO",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - Buông (Album 22 - Track No.02).mp3",
  },
  {
    idparent: "8",
    id: "47",
    name: `Em Là`,
    artist: "MONO, Onionn",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - Em Là (Album 22 - Track No.03).mp3",
  },
  {
    idparent: "8",
    id: "48",
    name: `Kill Me`,
    artist: "MONO",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - Kill Me (Album 22 - Track No.04).mp3",
  },
  {
    idparent: "8",
    id: "49",
    name: `Quên Anh Đi`,
    artist: "MONO",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - Quên Anh Đi (Album 22 - Track No.05).mp3",
  },
  {
    idparent: "8",
    id: "50",
    name: `Anh Không Thể`,
    artist: "MONO, Onionn",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - Anh Không Thể (Album 22 - Track No.07).mp3",
  },
  {
    idparent: "8",
    id: "51",
    name: `Do You`,
    artist: "MONO, Rein, Onionn",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO ft Rein - Do You (Album 22 - Track No.08).mp3",
  },
  {
    idparent: "8",
    id: "54",
    name: `L.I.E`,
    artist: "MONO, Onionn",
    image: "/Resources/Images2/22.jfif",
    path: "/Resources/22/MONO - L.I.E (Album 22 - Track No.11).mp3",
  },
  {
    idparent: "9",
    id: "17",
    name: `Chỉ Một Đêm Nữa Thôi`,
    artist: "RPT MCK, tlinh",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/06. Chỉ Một Đêm Nữa Thôi - RPT MCK ( ft. tlinh ) - - 99_ - the album.mp3",
  },
  {
    idparent: "9",
    id: "22",
    name: `Tại  Vì Sao`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/RPT MCK - TẠI VÌ SAO - Official Music Video.mp3",
  },
  {
    idparent: "9",
    id: "25",
    name: `Anh Đã Ổn Hơn`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/14. Anh Đã Ổn Hơn - RPT MCK - -99_- the album.mp3",
  },
  {
    idparent: "9",
    id: "23",
    name: `Thờ Er`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/RPT MCK - TẠI VÌ SAO - Official Music Video.mp3",
  },
  {
    idparent: "9",
    id: "24",
    name: `Ai Mới Là Kẻ Xâu Xa`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/RPT MCK - AI MỚI LÀ KẺ XẤU XA - OFFICIAL MUSIC VIDEO.mp3",
  },
  {
    idparent: "9",
    id: "13",
    name: `Chìm Sâu`,
    artist: "RPT MCK, Trung Trần",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/Chìm Sâu - RPT MCK (feat. Trung Trần) - Official Lyrics Video.mp3",
  },
  {
    idparent: "9",
    id: "14",
    name: `Suit & Tie`,
    artist: "RPT MCK, Hoàng Tôn",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/03. Suit & Tie - RPT MCK ( ft. Hoàng Tôn ) - - 99_ - the album.mp3",
  },
  {
    idparent: "9",
    id: "15",
    name: `Va Vào Giai Điệu Này`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/04. Va Vào Giai Điệu Này - RPT MCK - -99_- the album.mp3",
  },
  {
    idparent: "9",
    id: "16",
    name: `Tối Nay Ta Đi Đâu Nhỉ`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/Tối Nay Ta Đi Đâu Nhờ.mp3",
  },

  {
    idparent: "9",
    id: "18",
    name: `Thôi Em Đùng Đi`,
    artist: "RPT MCK, Trung Trần",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/07. Thôi Em Đừng Đi - RPT MCK ( ft. Trung Trần ) - - 99_ - the album.mp3",
  },
  {
    idparent: "9",
    id: "20",
    name: `Cuốn Cho Anh Một Điếu Nữa Đi`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/09. Cuốn Cho Anh Một Điếu Nữa Đi - RPT MCK - - 99_ - the album.mp3",
  },
  {
    idparent: "9",
    id: "21",
    name: `Show Me Love`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/10. Show Me Love - RPT MCK - - 99_ - the album.mp3",
  },
  {
    idparent: "9",
    id: "26",
    name: `Badtrip`,
    artist: "RPT MCK",
    image: "/Resources/Images2/99percent.jfif",
    path: "/Resources/99/15. Badtrip - RPT MCK - -99_- the album.mp3",
  },
  {
    idparent: "10",
    id: "37",
    name: `ghệ yêu dấu của em ơi`,
    artist: "tlinh, 2pillz, WOKEUP",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - ghệ iu dấu của em ơi - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "10",
    id: "38",
    name: `nếu lúc đó`,
    artist: "tlinh, 2pillz",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - nếu lúc đó - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "10",
    id: "31",
    name: `kho báu đánh rơi (feat.GREY D)`,
    artist: "tlinh, GREY D",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - kho báu đánh rơi (feat. Grey D) - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "10",
    id: "28",
    name: `tình yêu có nghĩa là gì?`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - người đẹp ngủ - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "10",
    id: "29",
    name: `người đẹp ngủ`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - người đẹp ngủ - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "10",
    id: "30",
    name: `người điên`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - người điên - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "10",
    id: "32",
    name: `ái`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - ái (interlude) - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "10",
    id: "33",
    name: `làm lành chữa tình`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - làm lành chữa tình - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "10",
    id: "34",
    name: `thế giới thần tiên`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - thế giới thần tiên - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "10",
    id: "35",
    name: `những đốm sáng`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - những đốm sáng - OFFICIAL VISUALIZER.mp3",
  },
  {
    idparent: "10",
    id: "36",
    name: `nữ siêu anh hùng`,
    artist: "tlinh",
    image: "/Resources/Images2/ai.jfif",
    path: "/Resources/ai/tlinh - nữ siêu anh hùng - OFFICIAL VISUALIZER.mp3",
  },

  {
    idparent: "11",
    id: "4",
    name: `Từng Quen`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/TỪNG QUEN - WREN EVANS X LIM FENG.mp3",
  },
  {
    idparent: "11",
    id: "11",
    name: `Phóng Đổ Tim Em`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - Phóng Đổ Tim Em - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "11",
    id: "2",
    name: `CALL ME`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - CALL ME - OFFICIAL MUSIC VIDEO.mp3",
  },
  {
    idparent: "11",
    id: "3",
    name: `Cầu Vĩnh Tuy`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - Cầu Vĩnh Tuy - LOI CHOI The First Album (ft. itsnk).mp3",
  },

  {
    idparent: "11",
    id: "5",
    name: `bé ơi từ từ`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - bé ơi từ từ - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "11",
    id: "6",
    name: `Lối Chơi (Interlude)`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - Lối Chơi (Interlude) - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "11",
    id: "7",
    name: `Tình Yêu Vĩ Mô`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - Tình Yêu Vĩ Mô - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "11",
    id: "8",
    name: `Việt Kiều`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - VIỆT KIỀU (ft. itsnk, starring @oanhdaqueen) - OFFICIAL MUSIC VIDEO.mp3",
  },
  {
    idparent: "11",
    id: "9",
    name: `ĐĐĐ`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - ĐĐĐ - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "11",
    id: "10",
    name: `Quyền Anh`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - Quyền Anh - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "11",
    id: "11",
    name: `Tò Te Tí`,
    artist: "Wren Evans, isnk",
    image: "/Resources/Images2/loiChoi.jfif",
    path: "/Resources/Musics/WREN EVANS - Tò Te Tí - LOI CHOI The First Album (ft. itsnk).mp3",
  },
  {
    idparent: "12",
    id: "61",
    name: `Không Thể Say`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Không Thể Say (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "12",
    id: "57",
    name: `Không Phải Gu`,
    artist: "HIEUTHUHAI,B Ray, Tage",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Không Phải Gu (prod. by Kewtiie) ft. B Ray & Tage [Official Lyric Video].mp3",
  },
  {
    idparent: "12",
    id: "64",
    name: `Sắp Nổi Tiếng`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Sắp Nổi Tiếng (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "12",
    id: "56",
    name: `Giờ Thì Ai Cười`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Giờ Thì Ai Cười (prod. by Kewtiie) [Official Lyric Video].mp3",
  },

  {
    idparent: "12",
    id: "58",
    name: `Siêu Sao`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Siêu Sao (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "12",
    id: "60",
    name: `Đi Họp Lớp`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Đi Họp Lớp (prod. by Kewtiie) [Official Lyric Video].mp3",
  },

  {
    idparent: "12",
    id: "62",
    name: `Exit Sign`,
    artist: "HIEUTHUHAI,marzuz",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Exit Sign (prod. by Kewtiie) ft. marzuz [Official Lyric Video].mp3",
  },
  {
    idparent: "12",
    id: "63",
    name: `Visa Interlude`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Visa Interlude (prod. by Kewtiie) [Official Audio].mp3",
  },

  {
    idparent: "12",
    id: "65",
    name: `KPI`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - KPI (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "12",
    id: "66",
    name: `Everything Will Be Okay`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Everything Will Be Okay (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "12",
    id: "67",
    name: `Cho Em An Toàn`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - Cho Em An Toàn (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
  {
    idparent: "12",
    id: "68",
    name: `NOLOVENOLIFE`,
    artist: "HIEUTHUHAI",
    image: "/Resources/Images2/aiCungPhai.jfif",
    path: "/Resources/aiCungPhai/HIEUTHUHAI - NOLOVENOLIFE (prod. by Kewtiie) [Official Lyric Video].mp3",
  },
];
//localStorage.removeItem("albums-detail");
localStorage.setItem("albums-detail", JSON.stringify(albums_detail));
location.reload;
